import { supabase } from '@/lib/supabase';

export async function listOrganizerCompetitions(organizerId: string) { const { data, error } = await supabase.from('competitions').select('*').eq('organizer_id', organizerId).order('created_at', { ascending: false }); if (error) throw error; return data ?? []; }
export async function listCompetitionRegistrations(competitionIds: string[]) { if (!competitionIds.length) return []; const { data, error } = await supabase.from('registrations').select('*').in('competition_id', competitionIds).order('created_at', { ascending: false }); if (error) throw error; return data ?? []; }
export async function reviewRegistration(id: string, status: 'APPROVED' | 'REJECTED', reason = '') { const { data, error } = await supabase.rpc('review_registration', { p_registration_id: id, p_decision: status, p_reason: reason.trim() || null }); if (error) throw error; return Array.isArray(data) ? data[0] : data; }
export async function listQuestionBanks(organizerId: string) { const { data, error } = await supabase.from('question_banks').select('*').eq('organizer_id', organizerId).order('created_at', { ascending: false }); if (error) throw error; return data ?? []; }
export async function listQuestions(questionBankId: string) { const { data, error } = await supabase.from('questions').select('id,type,prompt,points,required,display_order,status,config').eq('question_bank_id', questionBankId).order('display_order', { ascending: true }); if (error) throw error; return data ?? []; }
export async function listQuestionOptions(questionIds: string[]) { if (!questionIds.length) return []; const { data, error } = await supabase.from('question_options').select('id,question_id,label,value,is_correct,display_order').in('question_id', questionIds).order('display_order', { ascending: true }); if (error) throw error; return data ?? []; }
export async function saveQuestion(input: { id?: string; questionBankId: string; type: string; prompt: string; points?: number; required?: boolean; displayOrder?: number; status?: string; config?: Record<string, unknown>; options?: Array<{ label: string; value?: string; is_correct?: boolean; display_order?: number }> }) { const { data, error } = await supabase.rpc('save_question_with_options', { p_question_id: input.id ?? null, p_question_bank_id: input.questionBankId, p_type: input.type, p_prompt: input.prompt, p_points: input.points ?? 1, p_required: input.required ?? true, p_display_order: input.displayOrder ?? 0, p_status: input.status ?? 'DRAFT', p_config: input.config ?? {}, p_options: input.options ?? [] }); if (error) throw error; return data; }
export async function deleteQuestion(id: string) { const { error } = await supabase.from('questions').delete().eq('id', id); if (error) throw error; }
export async function gradeAttempt(attemptId: string) { const { data, error } = await supabase.rpc('grade_competition_attempt', { p_attempt_id: attemptId }); if (error) throw error; return data; }
