import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Calendar, Clock, FileText, Image as ImageIcon, Trophy, Users, ShieldCheck } from 'lucide-react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button } from '@/components/ui/Button';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { CommentsSection } from '@/components/ui/Comments';
import { useApp } from '@/store/AppContext';
import { getCompetitionBySlug, getCompetitionDetails } from '@/services/competition.service';
import { CATEGORY_LABELS, LEVEL_LABELS } from '@/data/catalog';
import { formatShortDate, countdown } from '@/lib/utils';

function statusUi(status: string){if(status==='REGISTRATION_OPEN')return{label:'Pendaftaran Dibuka',color:'moss' as const};if(status==='LIVE')return{label:'Sedang Berlangsung',color:'warn' as const};if(status==='RESULT_PUBLISHED'||status==='ARCHIVED')return{label:'Selesai',color:'default' as const};if(status==='REGISTRATION_CLOSED')return{label:'Pendaftaran Ditutup',color:'info' as const};return{label:'Segera Dibuka',color:'default' as const};}

export function CompetitionDetailPage(){
 const{slug=''}=useParams();const navigate=useNavigate();const{isGuest,user,feed}=useApp();const[detail,setDetail]=useState<any>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 useEffect(()=>{let active=true;(async()=>{setLoading(true);setError('');try{const base=await getCompetitionBySlug(slug);if(!base){if(active){setDetail(null);setError('Uji kompetensi tidak ditemukan.');}return;}const next=await getCompetitionDetails(String(base.id));if(active)setDetail(next);}catch(e:any){if(active)setError(e?.message??'Gagal memuat detail lomba.');}finally{if(active)setLoading(false);}})();return()=>{active=false;}},[slug]);
 const competition=detail?.competition;const rules=detail?.rules;const rewards=detail?.rewards??[];const levels=detail?.levels??[];const twibbons=detail?.twibbons??[];const[clock,setClock]=useState(Date.now());useEffect(()=>{const t=window.setInterval(()=>setClock(Date.now()),1000);return()=>window.clearInterval(t)},[]);void clock;
 const cd=competition?.registration_ends_at?countdown(String(competition.registration_ends_at)):{days:0,hours:0,minutes:0,seconds:0,expired:true};const joinable=competition?.status==='REGISTRATION_OPEN'&&!cd.expired;const category=CATEGORY_LABELS[String(competition?.category??'')]??String(competition?.category??'Kompetisi');const grades=useMemo(()=>[...new Set(levels.flatMap((l:any)=>l.allowed_grades??[]))],[levels]);const postId=feed.find(p=>p.competitionId===competition?.id)?.id;
 if(loading)return <div className="p-5 space-y-4"><div className="h-56 rounded-2xl bg-ink-800 animate-pulse"/><Card className="p-6"><div className="h-6 w-2/3 rounded bg-ink-800 animate-pulse"/><div className="h-4 w-1/2 rounded bg-ink-800 animate-pulse mt-3"/></Card></div>;
 if(!competition)return <div className="p-8 text-center"><Trophy size={36} className="mx-auto text-slate-600 mb-3"/><p className="text-slate-400">{error||'Uji kompetensi tidak ditemukan.'}</p><Button variant="ghost" className="mt-4" onClick={()=>navigate(-1)}>Kembali</Button></div>;
 const st=statusUi(String(competition.status));
 return <div className="pb-10"><div className="sticky top-0 z-20 glass border-b border-white/5 px-4 py-3 flex items-center gap-3"><button onClick={()=>navigate(-1)} className="p-2 rounded-lg hover:bg-white/5"><ArrowLeft size={19}/></button><div className="flex-1 min-w-0"><h2 className="font-display font-semibold text-sm text-white truncate">{competition.title}</h2><p className="text-xs text-slate-500">{Number(competition.participant_count??0).toLocaleString('id-ID')} peserta</p></div><Badge color={st.color}>{st.label}</Badge></div>
 <div className="relative h-56 md:h-72 bg-ink-800 overflow-hidden">{competition.poster_url?<img src={competition.poster_url} alt={competition.title} className="w-full h-full object-cover opacity-55"/>:<div className="w-full h-full flex items-center justify-center"><Trophy size={60} className="text-moss-500/30"/></div>}<div className="absolute inset-0 bg-gradient-to-t from-ink-950 via-ink-950/35 to-transparent"/><div className="absolute bottom-0 left-0 right-0 p-5"><div className="flex gap-2 mb-2"><Badge color={st.color}>{st.label}</Badge><Badge>{category}</Badge></div><h1 className="font-display text-2xl md:text-3xl font-bold text-white">{competition.title}</h1></div></div>
 <div className="p-4 space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Stat icon={<Users size={17}/>} label="Peserta" value={competition.participant_count}/><Stat icon={<Trophy size={17}/>} label="Soal aktif" value={detail?.questionCount??0}/><Stat icon={<Calendar size={17}/>} label="Mulai" value={formatShortDate(competition.starts_at)}/><Stat icon={<ShieldCheck size={17}/>} label="Kategori" value={category}/></div>
 {joinable&&<Card className="p-4 bg-moss-500/5 border-moss-500/20"><div className="flex items-center gap-2 mb-2"><Clock size={16} className="text-moss-400"/><p className="text-sm font-semibold text-white">Pendaftaran ditutup dalam</p></div><div className="grid grid-cols-4 gap-2">{[[cd.days,'Hari'],[cd.hours,'Jam'],[cd.minutes,'Menit'],[cd.seconds,'Detik']].map(([v,l])=><div key={String(l)} className="text-center"><div className="bg-ink-800/60 rounded-lg py-2"><span className="text-xl font-bold text-moss-300 tabular-nums">{String(v).padStart(2,'0')}</span></div><p className="text-[10px] text-slate-500 mt-1">{l}</p></div>)}</div></Card>}
 <Card className="p-4"><h3 className="font-display font-semibold text-white mb-2">Tentang Uji Kompetensi</h3><p className="text-sm text-slate-300 leading-relaxed whitespace-pre-line">{competition.description||competition.short_description||'Deskripsi belum tersedia.'}</p></Card>
 <Card className="p-4"><h3 className="font-display font-semibold text-white mb-3">Timeline</h3>{[['Pendaftaran dibuka',competition.registration_starts_at],['Batas pendaftaran',competition.registration_ends_at],['Uji kompetensi dimulai',competition.starts_at],['Uji kompetensi selesai',competition.ends_at],['Pengumuman',competition.announcement_at]].map(([label,date])=><div key={String(label)} className="flex items-center gap-3 py-2"><div className={`w-3 h-3 rounded-full ${date&&new Date(String(date)).getTime()<=Date.now()?'bg-moss-500':'bg-ink-600'}`}/><p className="flex-1 text-sm text-slate-300">{label}</p><span className="text-xs text-slate-500">{date?formatShortDate(String(date)):'—'}</span></div>)}</Card>
 <Card className="p-4"><h3 className="font-display font-semibold text-white mb-3">Eligibility & Aturan</h3><div className="flex flex-wrap gap-2">{grades.length?grades.map(g=><span key={String(g)} className="chip bg-moss-500/10 border border-moss-500/20 text-moss-300">{LEVEL_LABELS[String(g)]??String(g)}</span>):<span className="text-sm text-slate-500">Tidak dibatasi jenjang.</span>}</div>{rules&&<div className="grid sm:grid-cols-2 gap-3 mt-4"><Rule l="Approval" v={rules.approval_mode??'MANUAL'}/><Rule l="Maks peserta" v={rules.max_participants??'Tidak dibatasi'}/><Rule l="Twibbon" v={rules.require_twibbon?'Wajib':'Opsional'}/><Rule l="Social proof" v={rules.require_social_proof?'Wajib':'Opsional'}/></div>}</Card>
 <Card className="p-4"><h3 className="font-display font-semibold text-white mb-3 flex items-center gap-2"><Trophy size={16} className="text-amber-400"/> Hadiah</h3>{rewards.length?rewards.map((r:any)=><div key={r.id} className="flex items-center gap-3 rounded-xl bg-ink-800/40 p-3 mb-2 last:mb-0"><div className="w-9 h-9 rounded-lg bg-amber-500/10 flex items-center justify-center text-amber-300 font-bold">{r.rank_code??'•'}</div><div className="flex-1"><p className="text-sm font-semibold text-white">{r.title}</p><p className="text-xs text-slate-500">{r.emblem_name??'Tanpa emblem'}{r.certificate_enabled?' · Sertifikat':''}</p></div><span className="text-sm font-semibold text-moss-300">+{Number(r.points??0).toLocaleString('id-ID')} XP</span></div>):<p className="text-sm text-slate-500">Belum ada reward.</p>}</Card>
 <Card className="p-4"><h3 className="font-display font-semibold text-white mb-3 flex items-center gap-2"><ImageIcon size={16} className="text-moss-400"/> Twibbon</h3>{twibbons.length?<div className="grid sm:grid-cols-2 gap-3">{twibbons.map((t:any)=><div key={t.id} className="rounded-xl overflow-hidden border border-white/10"><img src={t.image_url} alt={t.name} loading="lazy" className="w-full aspect-video object-cover"/><div className="p-3 flex items-center justify-between"><span className="text-sm text-white">{t.name}</span>{t.is_required&&<Badge color="moss">Wajib</Badge>}</div></div>)}</div>:<p className="text-sm text-slate-500">Belum ada template twibbon aktif.</p>}</Card>
 <div className="flex gap-2">{joinable&&<Button fullWidth size="lg" disabled={isGuest||!user} onClick={()=>navigate(`/lomba/${competition.slug}/twibbon`)} icon={<Trophy size={17}/>} >{isGuest?'Masuk untuk Daftar':'Daftar Sekarang'}</Button>}{competition.status==='LIVE'&&Number(detail?.questionCount??0)>0&&<Button fullWidth size="lg" disabled={!user||isGuest} onClick={()=>navigate(`/lomba/${competition.slug}/kerja`)}>Kerjakan Uji Kompetensi</Button>}{competition.juknis_url&&<Button variant="outline" size="lg" onClick={()=>window.open(competition.juknis_url,'_blank')} icon={<FileText size={16}/>}>Juknis</Button>}</div>
 {postId?<Card className="p-4"><CommentsSection postId={postId}/></Card>:<Card className="p-4"><p className="text-xs text-slate-500">Komentar akan tersedia setelah postingan lomba dibuat.</p></Card>}
 </div></div>;
}
function Stat({icon,label,value}:{icon:React.ReactNode;label:string;value:any}){return <Card className="p-3"><div className="text-moss-400 mb-2">{icon}</div><p className="text-lg font-bold text-white truncate">{value==null||value===''?'—':typeof value==='number'?value.toLocaleString('id-ID'):String(value)}</p><p className="text-[11px] text-slate-500 mt-1">{label}</p></Card>}
function Rule({l,v}:{l:string;v:any}){return <div className="rounded-xl bg-ink-800/40 p-3"><p className="text-[10px] text-slate-500">{l}</p><p className="text-sm text-slate-200 mt-1">{String(v)}</p></div>}
