import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { Trophy, Users, School, Award, ArrowRight, Sparkles, Target, BookOpen } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Avatar } from '@/components/ui/Avatar';
import { RankBadge } from '@/components/ui/Badge';

export function HomePage(){
 const [stats,setStats]=useState<any>({});const [competitions,setCompetitions]=useState<any[]>([]);const [leaders,setLeaders]=useState<any[]>([]);const [slide,setSlide]=useState<any>(null);
 useEffect(()=>{let on=true;const load=async()=>{const [s,c,l,h]=await Promise.all([supabase.rpc('get_platform_stats'),supabase.rpc('get_public_competitions'),supabase.rpc('get_public_leaderboard',{p_limit:5}),supabase.from('home_slides').select('*').eq('is_active',true).order('sort_order').limit(1).maybeSingle()]);if(!on)return;setStats(s.data?.[0]||{});setCompetitions(c.data||[]);setLeaders(l.data||[]);setSlide(h.data||null)};void load();return()=>{on=false}},[]);
 return <div className="p-4 md:p-6 space-y-6"><section className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-br from-moss-500/10 via-ink-900 to-ink-950 p-6 md:p-9 min-h-[280px] flex items-center">{slide?.image_url&&<img src={slide.image_url} className="absolute inset-0 w-full h-full object-cover opacity-25"/>}<div className="relative max-w-2xl"><span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-moss-500/10 border border-moss-500/20 text-moss-300 text-xs font-semibold"><Sparkles size={13}/> SykaBelajar</span><h1 className="font-display text-3xl md:text-5xl font-bold text-white mt-4 leading-tight">Belajar, berkompetisi, dan tumbuh bersama.</h1><p className="text-slate-400 mt-3 max-w-xl">Ikuti uji kompetensi nyata, bangun rekam prestasi, kumpulkan XP dan Edu Coin dari aktivitas yang tercatat di backend.</p><div className="flex gap-2 mt-6"><Link to="/lomba"><Button icon={<Trophy size={16}/>}>Lihat Uji Kompetensi</Button></Link><Link to="/leaderboard"><Button variant="outline" icon={<ArrowRight size={16}/>}>Papan Peringkat</Button></Link></div></div></section>
 <section className="grid grid-cols-2 md:grid-cols-5 gap-3"><Stat icon={School} label="Sekolah Terdaftar" value={stats.total_schools}/><Stat icon={Users} label="Pelajar Terdaftar" value={stats.total_students}/><Stat icon={Users} label="User Terdaftar" value={stats.total_users}/><Stat icon={Trophy} label="Lomba Terdaftar" value={stats.total_competitions}/><Stat icon={Award} label="Sertifikat Terbit" value={stats.total_certificates}/></section>
 <section><div className="flex items-end justify-between mb-3"><div><p className="text-xs text-moss-400 font-semibold">UJI KOMPETENSI UNGGULAN</p><h2 className="font-display text-2xl font-bold text-white">Lomba publik yang sedang tersedia</h2></div><Link to="/lomba" className="text-sm text-moss-400">Lihat semua</Link></div><div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{competitions.slice(0,6).map(c=><Link key={c.id} to={`/lomba/${c.slug}`}><Card className="overflow-hidden hover:border-moss-500/30 transition h-full"><div className="aspect-[16/8] bg-ink-800">{c.poster_url?<img src={c.poster_url} className="w-full h-full object-cover"/>:<div className="h-full flex items-center justify-center"><Trophy className="text-moss-500/50" size={36}/></div>}</div><div className="p-4"><div className="flex items-center justify-between gap-2"><span className="text-[10px] text-moss-300 uppercase">{c.category}</span><span className="text-[10px] text-slate-500">{c.participant_count??0} peserta</span></div><h3 className="font-semibold text-white mt-2 line-clamp-2">{c.title}</h3><p className="text-xs text-slate-500 mt-1 line-clamp-2">{c.short_description}</p></div></Card></Link>)}{!competitions.length&&<Card className="p-8 col-span-full text-center text-slate-500">Belum ada lomba publik yang aktif di backend.</Card>}</div></section>
 <section className="grid lg:grid-cols-[1.5fr_1fr] gap-4"><Card className="p-5"><div className="flex items-center gap-2 mb-4"><Target size={18} className="text-moss-400"/><div><p className="text-xs text-slate-500">Aktivitas</p><h3 className="font-display font-bold text-white">Mulai dari sini</h3></div></div><div className="grid sm:grid-cols-3 gap-3"><Action to="/lomba" icon={Trophy} title="Ikuti Lomba" text="Temukan kompetisi aktif"/><Action to="/daily-tasks" icon={BookOpen} title="Daily Tasks" text="Bangun XP dari aktivitas"/><Action to="/leaderboard" icon={Award} title="Leaderboard" text="Lihat posisi kamu"/></div></Card><Card className="p-5"><div className="flex justify-between items-center mb-4"><h3 className="font-display font-bold text-white">Top 5 XP Global</h3><Link to="/leaderboard" className="text-xs text-moss-400">Semua</Link></div><div className="space-y-2.5">{leaders.map((u:any)=><div key={u.user_id} className="flex items-center gap-2"><RankBadge rank={Number(u.rank)} size="sm"/><Avatar name={u.display_name||u.username} id={u.user_id} size={32} src={u.avatar_url||undefined} className="rounded-lg"/><div className="flex-1 min-w-0"><p className="text-sm text-white truncate">{u.display_name||u.username}</p><p className="text-[10px] text-slate-500 truncate">{u.institution||'—'}</p></div><span className="text-xs text-moss-300 font-semibold">{Number(u.xp||0).toLocaleString('id-ID')} XP</span></div>)}{!leaders.length&&<p className="text-sm text-slate-500">Belum ada data XP.</p>}</div></Card></section></div>;
}
function Stat({icon:Icon,label,value}:{icon:any;label:string;value:any}){return <Card className="p-4"><Icon size={17} className="text-moss-400 mb-3"/><p className="text-xl font-bold text-white">{Number(value||0).toLocaleString('id-ID')}</p><p className="text-[11px] text-slate-500 mt-1">{label}</p></Card>}
function Action({to,icon:Icon,title,text}:{to:string;icon:any;title:string;text:string}){return <Link to={to} className="rounded-xl border border-white/5 bg-ink-800/40 p-3 hover:border-moss-500/20"><Icon size={18} className="text-moss-400"/><p className="text-sm text-white font-semibold mt-3">{title}</p><p className="text-[11px] text-slate-500 mt-1">{text}</p></Link>}
