import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { TrendingUp, TrendingDown, Minus } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { Avatar } from '@/components/ui/Avatar';
import { RankBadge } from '@/components/ui/Badge';
import { getPublicLeaderboard, type PublicLeaderboardRow } from '@/services/platform.service';
import { useApp } from '@/store/AppContext';
type TabValue='global'|'student';
export function LeaderboardPage(){const{user}=useApp();const[entries,setEntries]=useState<PublicLeaderboardRow[]>([]);const[tab,setTab]=useState<TabValue>('global');const[loading,setLoading]=useState(true);useEffect(()=>{let active=true;const load=async()=>{setLoading(true);try{const rows=await getPublicLeaderboard(100);if(active)setEntries(rows)}catch(error){console.error('[SykaBelajar] leaderboard live data failed',error);if(active)setEntries([])}finally{if(active)setLoading(false)}};void load();return()=>{active=false}},[]);const filtered=tab==='global'?entries:entries;const top3=filtered.slice(0,3);const rest=filtered.slice(3);return <div><div className="sticky top-0 z-20 glass border-b border-white/5 px-4 py-3"><h2 className="font-display font-bold text-lg text-white">Papan Peringkat</h2><div className="flex items-center gap-1.5 mt-2"><button onClick={()=>setTab('global')} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${tab==='global'?'bg-moss-500/15 text-moss-300':'text-slate-500'}`}>Global</button><button onClick={()=>setTab('student')} className={`px-3 py-1.5 rounded-lg text-xs font-medium ${tab==='student'?'bg-moss-500/15 text-moss-300':'text-slate-500'}`}>Pelajar</button><span className="ml-auto flex items-center gap-1 text-xs text-moss-400"><span className="w-2 h-2 rounded-full bg-moss-400 animate-pulse"/>Live</span></div></div><div className="p-4 space-y-4">{loading&&<Card className="p-8 text-center text-sm text-slate-500">Memuat papan peringkat dari backend...</Card>}{!loading&&top3.length>=3&&<div className="grid grid-cols-3 gap-2"><TopBox entry={top3[1]} place={2}/><TopBox entry={top3[0]} place={1}/><TopBox entry={top3[2]} place={3}/></div>}{!loading&&<div className="space-y-2">{rest.map(entry=><LeaderboardRow key={entry.user_id} entry={entry} currentUserId={user?.id}/>)}</div>}{!loading&&!entries.length&&<Card className="p-8 text-center text-sm text-slate-500">Belum ada data XP publik.</Card>}<p className="text-center text-xs text-slate-600 pt-4">Peringkat dan perubahan poin berasal dari XP ledger backend.</p></div></div>}
function TopBox({entry,place}:{entry:PublicLeaderboardRow;place:1|2|3}){const styles=place===1?'border-amber-500/40':place===2?'border-slate-400/30':'border-orange-600/30';return <div className="flex flex-col"><div className={`card p-3 flex flex-col items-center ${styles}`}><div className="relative w-full mb-2"><div className="rounded-xl overflow-hidden bg-ink-800" style={{aspectRatio:'4/5'}}><Avatar name={entry.display_name} id={entry.user_id} size={160} src={entry.avatar_url??undefined} shape="square"/></div><div className="absolute -bottom-1.5 -right-1.5"><RankBadge rank={place} size="sm"/></div></div><Link to={`/profile/${entry.username}`} className="text-center w-full"><p className="text-xs font-bold text-white truncate">{entry.display_name}</p><p className="text-[10px] text-slate-500 truncate">{entry.institution||'—'}</p></Link><RankStatus status={entry.rank_change} pointChange={entry.point_change} className="mt-2"/><p className="mt-1 text-sm font-bold text-moss-300">{entry.xp.toLocaleString('id-ID')} XP</p></div></div>}
function LeaderboardRow({entry,currentUserId}:{entry:PublicLeaderboardRow;currentUserId?:string}){return <Card className={`p-3 ${currentUserId===entry.user_id?'border-moss-500/40 bg-moss-500/5':''}`}><div className="flex items-center gap-3"><div className="w-8 text-center"><span className="text-sm font-bold text-slate-300">{entry.rank}</span></div><Link to={`/profile/${entry.username}`}><Avatar name={entry.display_name} id={entry.user_id} size={36} ring={currentUserId===entry.user_id} src={entry.avatar_url??undefined} shape="square"/></Link><div className="flex-1 min-w-0"><Link to={`/profile/${entry.username}`}><p className={`text-sm font-semibold truncate ${currentUserId===entry.user_id?'text-moss-300':'text-white'}`}>{entry.display_name}{currentUserId===entry.user_id?' (Kamu)':''}</p><p className="text-xs text-slate-500 truncate">{entry.institution||'—'}</p></Link></div><RankStatus status={entry.rank_change} pointChange={entry.point_change}/><span className="text-sm font-semibold text-moss-300 tabular-nums w-20 text-right">{entry.xp.toLocaleString('id-ID')} XP</span></div></Card>}
function RankStatus({status,pointChange,className=''}:{status:PublicLeaderboardRow['rank_change'];pointChange:number;className?:string}){const Icon=status==='up'?TrendingUp:status==='down'?TrendingDown:Minus;const iconClass=status==='up'?'text-green-400':status==='down'?'text-red-400':'text-slate-500';const pointClass=pointChange>0?'text-green-400':pointChange<0?'text-red-400':'text-slate-500';const pointText=pointChange>0?`+${pointChange}`:String(pointChange);return <div className={`flex items-center gap-1.5 shrink-0 ${className}`}><Icon size={14} className={iconClass}/><span className={`text-xs font-medium ${pointClass}`}>{pointText}</span></div>}
