import { useEffect, useState } from 'react';
import { Building2, Trophy, Users, FileQuestion, Image, ShoppingBag, Settings, Plus, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';

export function OrganizerPage(){
 const [organizer,setOrganizer]=useState<any>(null); const [competitions,setCompetitions]=useState<any[]>([]); const [members,setMembers]=useState<any[]>([]); const [plans,setPlans]=useState<any[]>([]); const [registrations,setRegistrations]=useState<any[]>([]); const [tab,setTab]=useState('overview'); const [busy,setBusy]=useState(false);
 const load=async()=>{const {data:user}=await supabase.auth.getUser();if(!user.user)return;const {data:o}=await supabase.from('organizers').select('*').eq('owner_user_id',user.user.id).maybeSingle();if(!o){setOrganizer(null);return;}setOrganizer(o);const [c,m,p,r]=await Promise.all([supabase.from('competitions').select('*').eq('organizer_id',o.id).order('created_at',{ascending:false}),supabase.from('organizer_members').select('*').eq('organizer_id',o.id),supabase.from('organizer_plans').select('*').eq('organizer_id',o.id),supabase.from('registrations').select('id,competition_id,user_id,status,submitted_at,metadata').in('competition_id',(await supabase.from('competitions').select('id').eq('organizer_id',o.id)).data?.map(x=>x.id)||[]).order('created_at',{ascending:false})]);setCompetitions(c.data||[]);setMembers(m.data||[]);setPlans(p.data||[]);setRegistrations(r.data||[])};useEffect(()=>{void load()},[]);
 const transition=async(id:string,status:any)=>{setBusy(true);const {error}=await supabase.rpc('transition_competition',{p_competition_id:id,p_to_status:status,p_reason:'Organizer dashboard'});setBusy(false);if(error)alert(error.message);else void load()};
 if(!organizer)return <div className="p-6"><Card className="p-8 text-center"><Building2 size={30} className="mx-auto text-moss-400 mb-3"/><h2 className="text-white font-bold">Panel Penyelenggara</h2><p className="text-sm text-slate-500 mt-2">Akun ini belum memiliki organisasi yang terhubung di backend.</p></Card></div>;
 const tabs=[['overview','Ringkasan',Building2],['competitions','Lomba',Trophy],['registrations','Pendaftar',Users],['questions','Bank Soal',FileQuestion],['twibbon','Twibbon',Image],['plans','Plan & Usage',Settings]];
 return <div className="min-h-screen flex bg-ink-950"><aside className="w-56 shrink-0 border-r border-white/5 p-3 sticky top-0 h-screen"><div className="px-3 py-3"><p className="text-xs text-moss-400">ORGANIZER</p><h1 className="text-lg font-bold text-white truncate">{organizer.name}</h1></div>{tabs.map(([k,l,I]:any)=><button key={k} onClick={()=>setTab(k)} className={`w-full flex gap-3 items-center px-3 py-2.5 rounded-xl text-sm ${tab===k?'bg-moss-500/10 text-moss-300':'text-slate-400 hover:bg-white/5'}`}><I size={17}/>{l}</button>)}<Link to="/home" className="block px-3 mt-5 text-xs text-slate-500">← Kembali</Link></aside><section className="flex-1 p-5 md:p-7 overflow-auto"><div className="flex justify-between mb-6"><div><h2 className="font-display text-2xl font-bold text-white">{tabs.find(t=>t[0]===tab)?.[1]}</h2><p className="text-xs text-slate-500">{organizer.name} · data live Supabase</p></div><Badge color="moss">{organizer.status}</Badge></div>
 {tab==='overview'&&<div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Metric label="Lomba" value={competitions.length}/><Metric label="Pendaftar" value={registrations.length}/><Metric label="Member" value={members.length}/><Metric label="Plan" value={plans.find(p=>p.is_active)?.plan_code||'—'}/></div>}
 {tab==='competitions'&&<div className="space-y-3">{competitions.map(c=><Card key={c.id} className="p-4 flex gap-3 items-center"><div className="w-11 h-11 rounded-xl bg-moss-500/10 flex items-center justify-center"><Trophy size={19} className="text-moss-400"/></div><div className="flex-1"><p className="text-white font-semibold">{c.title}</p><p className="text-xs text-slate-500">{c.slug} · {c.status}</p></div><select className="input w-48" value={c.status} disabled={busy} onChange={e=>void transition(c.id,e.target.value)}><option>DRAFT</option><option>PUBLISHED</option><option>REGISTRATION_OPEN</option><option>REGISTRATION_CLOSED</option><option>LIVE</option><option>SUBMISSION_CLOSED</option><option>GRADING</option><option>RESULT_PUBLISHED</option><option>ARCHIVED</option></select></Card>)}<Button icon={<Plus size={15}/>} onClick={()=>alert('Form builder lomba akan memakai tabel competitions + competition_levels + registration_rules + rewards; tidak membuat dummy data.')}>Tambah Lomba</Button></div>}
 {tab==='registrations'&&<div className="space-y-2">{registrations.map(r=><Card key={r.id} className="p-4 flex items-center gap-3"><Users size={17} className="text-slate-500"/><div className="flex-1"><p className="text-sm text-white">Pendaftar {r.user_id.slice(0,8)}</p><p className="text-xs text-slate-500">Lomba {r.competition_id.slice(0,8)} · {new Date(r.submitted_at).toLocaleString('id-ID')}</p></div><Badge>{r.status}</Badge></Card>)}{!registrations.length&&<Card className="p-8 text-center text-slate-500">Belum ada pendaftar.</Card>}</div>}
 {tab==='questions'&&<Card className="p-5"><FileQuestion size={25} className="text-moss-400 mb-3"/><h3 className="text-white font-semibold">Bank Soal</h3><p className="text-sm text-slate-500 mt-1">Kelola `question_banks`, `questions`, dan `question_options` dari sini. Soal peserta tidak boleh mengekspos jawaban benar.</p><Button className="mt-4" onClick={()=>alert('Question bank CRUD akan ditulis langsung ke backend organizer.')}>Buka Bank Soal</Button></Card>}
 {tab==='twibbon'&&<Card className="p-5"><Image size={25} className="text-moss-400 mb-3"/><h3 className="text-white font-semibold">Template Twibbon</h3><p className="text-sm text-slate-500">Sumber: `twibbon_templates` + Cloudinary. Template kosong di backend saat ini.</p></Card>}
 {tab==='plans'&&<div className="space-y-3">{plans.map(p=><Card key={p.id} className="p-4 flex justify-between"><div><p className="text-white font-semibold">{p.plan_code}</p><p className="text-xs text-slate-500">{new Date(p.starts_at).toLocaleDateString('id-ID')} — {p.ends_at?new Date(p.ends_at).toLocaleDateString('id-ID'):'aktif'}</p></div><Badge color={p.is_active?'moss':'default'}>{p.is_active?'Digunakan':'Tidak aktif'}</Badge></Card>)}</div>}
 </section></div>;
}
function Metric({label,value}:{label:string;value:any}){return <Card className="p-4"><p className="text-xs text-slate-500">{label}</p><p className="text-2xl font-bold text-white mt-1">{String(value)}</p></Card>}
