import { useEffect, useState } from 'react';
import { ArrowLeft, CheckCircle2, Gauge, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Card } from '@/components/ui/Card';
import { Badge } from '@/components/ui/Badge';
import { supabase } from '@/lib/supabase';
import { getActiveOrganizerEntitlements, type OrganizerEntitlement } from '@/services/organizerEntitlement.service';

export function OrganizerPlanPage(){const[plan,setPlan]=useState<string|null>(null);const[items,setItems]=useState<OrganizerEntitlement[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');useEffect(()=>{let active=true;void(async()=>{try{const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('Sesi login tidak tersedia.');const{data:org,error:orgError}=await supabase.from('organizers').select('id').eq('owner_user_id',auth.user.id).maybeSingle();if(orgError)throw orgError;if(!org)throw new Error('Organisasi tidak ditemukan.');const result=await getActiveOrganizerEntitlements(org.id);if(active){setPlan(result.planCode);setItems(result.entitlements)}}catch(e:any){if(active)setError(e?.message??'Gagal memuat plan.')}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);return <div className="min-h-screen bg-ink-950 text-slate-200 p-5 md:p-8"><div className="max-w-5xl mx-auto"><Link to="/organizer" className="inline-flex items-center gap-2 text-xs text-slate-500 hover:text-white mb-5"><ArrowLeft size={14}/> Kembali ke Penyelenggara</Link><div className="mb-6"><p className="text-xs text-moss-400 font-semibold">PENYELENGGARA · PLAN</p><h1 className="font-display text-2xl font-bold text-white">Plan & Usage</h1><p className="text-sm text-slate-500 mt-1">Capability dan limit diambil langsung dari backend.</p></div>{error&&<Card className="p-4 border-red-500/20 text-red-300 mb-4">{error}</Card>}{loading?<Card className="p-8 text-center text-slate-500">Memuat entitlement…</Card>:<><Card className="p-5 mb-4"><div className="flex items-center gap-3"><ShieldCheck className="text-moss-400"/><div className="flex-1"><p className="text-xs text-slate-500">Plan aktif</p><p className="text-xl font-bold text-white">{plan??'Belum ada plan aktif'}</p></div><Badge color={plan?'moss':'default'}>{plan?'ACTIVE':'INACTIVE'}</Badge></div></Card><div className="grid sm:grid-cols-2 gap-3">{items.map((item)=><Card key={item.capability} className="p-4"><div className="flex items-start gap-3"><Gauge size={17} className="text-moss-400 mt-0.5"/><div className="flex-1"><p className="text-sm font-semibold text-white">{item.capability}</p><p className="text-xs text-slate-500 mt-1">{item.limit_value==null?'Tanpa limit numerik':`Limit: ${item.limit_value.toLocaleString('id-ID')}`}</p>{Object.keys(item.config).length>0&&<p className="text-[11px] text-slate-600 mt-2">Konfigurasi backend tersedia</p>}</div><CheckCircle2 size={15} className="text-moss-400"/></div></Card>)}{!items.length&&<Card className="p-8 text-center text-slate-500 sm:col-span-2">Belum ada entitlement plan aktif.</Card>}</div></>}</div></div>}
