import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, Building2, Camera, Check, GraduationCap, School, User as UserIcon } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { Avatar } from '@/components/ui/Avatar';
import { Button } from '@/components/ui/Button';
import { useApp } from '@/store/AppContext';
import { CATEGORY_LABELS, LEVEL_LABELS } from '@/data/catalog';
import { uploadImage } from '@/services/cloudinary.service';
import { updateProfile } from '@/services/profile.service';
import { supabase } from '@/lib/supabase';
import type { CompetitionCategory, EducationLevel, Role } from '@/types';

const ROLE_OPTIONS: { value: Exclude<Role,'admin'>; label:string; icon:typeof UserIcon }[]=[{value:'pelajar',label:'Pelajar',icon:UserIcon},{value:'guru',label:'Guru',icon:School},{value:'penyelenggara',label:'Penyelenggara',icon:Building2}];

export function RegisterPage(){
 const navigate=useNavigate(); const {register,toast}=useApp(); const fileRef=useRef<HTMLInputElement>(null); const [step,setStep]=useState(1); const [loading,setLoading]=useState(false); const [photoFile,setPhotoFile]=useState<File|null>(null); const [photoPreview,setPhotoPreview]=useState<string>('');
 const [form,setForm]=useState({email:'',password:'',confirmPassword:'',role:'pelajar' as Exclude<Role,'admin'>,displayName:'',username:'',birthDate:'',school:'',educationLevel:'' as EducationLevel|'',favoriteCategories:[] as CompetitionCategory[]});
 useEffect(()=>{return()=>{if(photoPreview)URL.revokeObjectURL(photoPreview)}},[photoPreview]);
 const set=(k:keyof typeof form,v:any)=>setForm(f=>({...f,[k]:v}));
 const toggleCategory=(category:CompetitionCategory)=>setForm(f=>({...f,favoriteCategories:f.favoriteCategories.includes(category)?f.favoriteCategories.filter(x=>x!==category):[...f.favoriteCategories,category]}));
 const step1Valid=form.email.includes('@')&&form.password.length>=6&&form.password===form.confirmPassword;
 const step2Valid=!!form.displayName&&!!form.username&&!!form.birthDate&&!!form.school&&(form.role==='guru'||!!form.educationLevel);
 const choosePhoto=(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')||file.size>5*1024*1024){toast('Foto harus gambar dan maksimal 5MB.','error');return;}if(photoPreview)URL.revokeObjectURL(photoPreview);setPhotoFile(file);setPhotoPreview(URL.createObjectURL(file));e.target.value='';};
 const handleSubmit=async()=>{if(!form.favoriteCategories.length){toast('Pilih minimal 1 kategori lomba favorit.','error');return;}setLoading(true);try{
   const result=await register({email:form.email,password:form.password,displayName:form.displayName,username:form.username,role:form.role,school:form.school,birthDate:form.birthDate,educationLevel:form.educationLevel||undefined,favoriteCategories:form.favoriteCategories});
   if(!result.ok){toast(result.error||'Pendaftaran gagal.','error');return;}
   // Upload only after Supabase account creation has succeeded.
   if(photoFile){const {data}=await supabase.auth.getSession(); if(data.session?.user){const up=await uploadImage(photoFile,`sykabelajar/users/profiles/${data.session.user.id}`);await updateProfile(data.session.user.id,{avatar_url:up.secure_url,avatar_public_id:up.public_id,avatar_width:up.width,avatar_height:up.height,avatar_version:up.version?String(up.version):null,avatar_resource_type:up.resource_type||'image'});}else{toast('Akun berhasil dibuat. Foto profil akan diunggah setelah konfirmasi email dan login pertama.','info');}}
   toast('Pendaftaran berhasil. Silakan masuk.','success');navigate('/login');
 }catch(error:any){toast(error?.message||'Pendaftaran gagal.','error')}finally{setLoading(false)}};
 return <div className="min-h-screen flex flex-col"><header className="px-4 h-16 flex items-center justify-between border-b border-white/5"><Link to="/" className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg gradient-moss flex items-center justify-center"><GraduationCap size={16} className="text-white"/></div><span className="font-display font-bold text-white">sykabelajar<span className="text-moss-400">.id</span></span></Link><Link to="/login" className="text-sm text-slate-400">Sudah punya akun? <span className="text-moss-400">Masuk</span></Link></header><div className="flex-1 flex items-center justify-center px-4 py-10"><div className="w-full max-w-md"><div className="flex gap-2 mb-8">{[1,2,3].map(s=><div key={s} className="flex-1 h-1.5 rounded-full bg-ink-700 overflow-hidden"><div className={`h-full ${s<=step?'gradient-moss w-full':'w-0'}`}/></div>)}</div>
 {step===1&&<div className="card p-6"><h1 className="font-display font-bold text-2xl text-white">Buat Akun</h1><p className="text-sm text-slate-400 mt-1">Akun dibuat terlebih dahulu sebelum media diupload.</p><div className="space-y-4 mt-6"><div><label className="label">Email</label><input className="input" type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></div><div><label className="label">Password</label><input className="input" type="password" value={form.password} onChange={e=>set('password',e.target.value)}/></div><div><label className="label">Konfirmasi Password</label><input className="input" type="password" value={form.confirmPassword} onChange={e=>set('confirmPassword',e.target.value)}/></div></div><Button fullWidth size="lg" className="mt-6" disabled={!step1Valid} onClick={()=>setStep(2)} icon={<ArrowRight size={18}/>}>Lanjut</Button></div>}
 {step===2&&<div className="card p-6"><h1 className="font-display font-bold text-2xl text-white">Tentang Kamu</h1><p className="text-sm text-slate-400 mt-1">Role disimpan di backend Supabase.</p><div className="space-y-4 mt-6"><div><label className="label">Saya adalah</label><div className="grid grid-cols-3 gap-2">{ROLE_OPTIONS.map(({value,label,icon:Icon})=><button key={value} type="button" onClick={()=>set('role',value)} className={`p-3 rounded-xl border flex flex-col items-center gap-2 ${form.role===value?'border-moss-500 bg-moss-500/10':'border-white/10'}`}><Icon size={20}/><span className="text-xs">{label}</span></button>)}</div></div><div><label className="label">Foto Profil</label><div className="flex items-center gap-4"><div className="relative">{photoPreview?<img src={photoPreview} alt="Preview" className="w-16 h-16 rounded-full object-cover"/>:<Avatar name={form.displayName||'U'} id="register-preview" size={64}/>}<button type="button" onClick={()=>fileRef.current?.click()} className="absolute -bottom-1 -right-1 w-7 h-7 rounded-full bg-moss-600 flex items-center justify-center border-2 border-ink-900"><Camera size={13}/></button></div><div><button type="button" onClick={()=>fileRef.current?.click()} className="text-xs text-moss-400">{photoFile?'Ganti foto':'Pilih foto (opsional)'}</button><p className="text-[10px] text-slate-600">Preview lokal; upload setelah akun sukses.</p></div></div><input ref={fileRef} type="file" accept="image/*" onChange={choosePhoto} className="hidden"/></div><div><label className="label">Nama Lengkap</label><input className="input" value={form.displayName} onChange={e=>set('displayName',e.target.value)}/></div><div><label className="label">Username</label><input className="input" value={form.username} onChange={e=>set('username',e.target.value.replace(/\s/g,'').toLowerCase())}/></div><div><label className="label">Tanggal Lahir</label><input type="date" className="input" value={form.birthDate} onChange={e=>set('birthDate',e.target.value)}/></div><div><label className="label">Sekolah / Institusi</label><input className="input" value={form.school} onChange={e=>set('school',e.target.value)}/></div>{form.role==='pelajar'&&<div><label className="label">Jenjang</label><select className="input" value={form.educationLevel} onChange={e=>set('educationLevel',e.target.value as EducationLevel)}><option value="">Pilih jenjang...</option>{Object.entries(LEVEL_LABELS).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>}</div><div className="flex gap-2 mt-6"><Button variant="outline" onClick={()=>setStep(1)} icon={<ArrowLeft size={18}/>}>Kembali</Button><Button fullWidth disabled={!step2Valid} onClick={()=>setStep(3)}>Lanjut</Button></div></div>}
 {step===3&&<div className="card p-6"><h1 className="font-display font-bold text-2xl text-white">Kategori Favorit</h1><p className="text-sm text-slate-400 mt-1">Pilih minimal satu.</p><div className="grid grid-cols-2 gap-2 mt-6">{Object.entries(CATEGORY_LABELS).map(([key,label])=>{const selected=form.favoriteCategories.includes(key as CompetitionCategory);return <button key={key} onClick={()=>toggleCategory(key as CompetitionCategory)} className={`p-3 rounded-xl border text-sm flex items-center justify-between ${selected?'border-moss-500 bg-moss-500/10 text-moss-300':'border-white/10 text-slate-300'}`}>{label}{selected&&<Check size={16}/>}</button>})}</div><div className="flex gap-2 mt-6"><Button variant="outline" onClick={()=>setStep(2)} icon={<ArrowLeft size={18}/>}>Kembali</Button><Button fullWidth loading={loading} onClick={()=>void handleSubmit()}>Buat Akun</Button></div></div>}
 <p className="text-xs text-slate-600 text-center mt-4">Admin hanya dapat diberikan manual melalui backend.</p></div></div></div>;
}
