import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ExternalLink, ImagePlus, RefreshCw, Upload } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { supabase } from '@/lib/supabase';
import { uploadImage, deleteImage } from '@/services/cloudinary.service';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { useApp } from '@/store/AppContext';
import { getCompetitionBySlug } from '@/services/competition.service';
import { submitRegistration } from '@/services/registration.service';

export function TwibbonPage(){
 const{slug=''}=useParams();const navigate=useNavigate();const{user,toast}=useApp();const[file,setFile]=useState<File|null>(null);const[preview,setPreview]=useState('');const[templates,setTemplates]=useState<any[]>([]);const[registration,setRegistration]=useState<any>(null);const[postUrl,setPostUrl]=useState('');const[platform,setPlatform]=useState<'instagram'|'tiktok'>('instagram');const[socialUsername,setSocialUsername]=useState('');const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);
 useEffect(()=>{if(!file)return;const u=URL.createObjectURL(file);setPreview(u);return()=>URL.revokeObjectURL(u)},[file]);
 const load=async()=>{if(!user?.id)return;setLoading(true);try{const c=await getCompetitionBySlug(slug);if(!c){toast('Lomba tidak ditemukan.','error');return;}const[{data:t},{data:r}]=await Promise.all([supabase.from('twibbon_templates').select('*').eq('competition_id',c.id).eq('is_active',true).order('created_at',{ascending:false}),supabase.from('registrations').select('*').eq('competition_id',c.id).eq('user_id',user.id).order('created_at',{ascending:false}).limit(1).maybeSingle()]);setTemplates(t??[]);setRegistration(r);setPostUrl(r?.social_proof_url??'');setPlatform(r?.metadata?.social_platform==='tiktok'?'tiktok':'instagram');setSocialUsername(r?.metadata?.social_username??'');return c;}catch(e:any){toast(e?.message??'Gagal memuat Twibbon.','error');}finally{setLoading(false)}};
 const submit=async()=>{if(!user)return;setSaving(true);try{const c=await getCompetitionBySlug(slug);if(!c)throw new Error('Lomba tidak ditemukan.');let reg=registration;if(!reg){const created=await submitRegistration({competitionId:c.id,userId:user.id,socialPlatform:platform,socialUsername, socialProofUrl:postUrl});reg=created.record;setRegistration(reg);}let oldPublicId=reg?.twibbon_public_id as string|undefined; if(file){const up=await uploadImage(file,`sykabelajar/twibbon/${c.id}/${user.id}`);const{error}=await supabase.from('registrations').update({twibbon_asset_url:up.secure_url,twibbon_public_id:up.public_id,metadata:{...(reg?.metadata??{}),social_platform:platform,social_username:socialUsername.trim().replace(/^@+/, '')},updated_at:new Date().toISOString()}).eq('id',reg.id).eq('user_id',user.id);if(error)throw error;if(oldPublicId&&oldPublicId!==up.public_id)void deleteImage(oldPublicId);setRegistration({...reg,twibbon_asset_url:up.secure_url,twibbon_public_id:up.public_id});setFile(null);}else if(reg){const{error}=await supabase.from('registrations').update({social_proof_url:postUrl.trim(),metadata:{...(reg.metadata??{}),social_platform:platform,social_username:socialUsername.trim().replace(/^@+/, '')},submitted_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',reg.id).eq('user_id',user.id);if(error)throw error;} toast('Pendaftaran dan bukti tersimpan. Status menunggu verifikasi.','success');await load();}catch(e:any){toast(e?.message??'Gagal menyimpan pendaftaran.','error')}finally{setSaving(false)}};
 if(!user)return <div className="p-8 text-center text-slate-400">Silakan login terlebih dahulu.</div>;
 return <div className="min-h-screen p-4 md:p-6"><div className="max-w-5xl mx-auto space-y-4"><div className="flex items-center gap-3"><button onClick={()=>navigate(-1)} className="p-2 rounded-lg hover:bg-white/5"><ArrowLeft size={19}/></button><div className="flex-1"><p className="text-xs text-moss-400 uppercase">Twibbon</p><h1 className="font-display text-2xl font-bold text-white">Kirim bukti pendaftaran</h1></div><Button variant="outline" onClick={()=>void load()} loading={loading} icon={<RefreshCw size={14}/>}>Refresh</Button></div>
 <Card className="p-5"><h2 className="font-semibold text-white">1. Template aktif</h2><div className="grid sm:grid-cols-2 gap-3 mt-4">{templates.map(t=><a href={t.image_url} target="_blank" rel="noreferrer" key={t.id} className="rounded-xl border border-white/10 overflow-hidden"><img src={t.image_url} alt={t.name} className="aspect-video w-full object-cover"/><div className="p-3 flex items-center justify-between"><span className="text-sm text-white">{t.name}</span><ExternalLink size={14}/></div></a>)}{!templates.length&&<p className="text-sm text-slate-500">Belum ada template aktif.</p>}</div></Card>
 <Card className="p-5"><h2 className="font-semibold text-white">2. Pilih foto</h2><p className="text-xs text-slate-500 mt-1">Foto hanya preview lokal sampai kamu menekan tombol Kirim. Tidak ada upload saat memilih file.</p><div className="mt-4 flex flex-col sm:flex-row gap-4 items-start"><div className="w-full sm:w-72 aspect-square rounded-xl border border-white/10 bg-ink-800 overflow-hidden flex items-center justify-center">{preview?<img src={preview} alt="Preview lokal" className="w-full h-full object-cover"/>:registration?.twibbon_asset_url?<img src={registration.twibbon_asset_url} alt="Bukti tersimpan" className="w-full h-full object-cover"/>:<ImagePlus size={36} className="text-slate-600"/>}</div><div className="space-y-3"><label className="inline-flex items-center gap-2 px-4 py-2.5 rounded-xl bg-moss-600 text-white text-sm cursor-pointer"><Upload size={16}/><span>{file?'Ganti foto':'Pilih foto'}</span><input type="file" accept="image/*" className="hidden" disabled={saving} onChange={e=>setFile(e.target.files?.[0]??null)}/></label>{registration?.twibbon_asset_url&&<p className="text-xs text-slate-500">Bukti saat ini tersimpan di Cloudinary. Saat diganti, asset lama akan dicoba dihapus setelah asset baru berhasil disimpan.</p>}</div></div></Card>
 <Card className="p-5"><h2 className="font-semibold text-white">3. Social proof</h2><div className="grid sm:grid-cols-2 gap-3 mt-4"><select className="input" value={platform} onChange={e=>setPlatform(e.target.value as any)}><option value="instagram">Instagram</option><option value="tiktok">TikTok</option></select><input className="input" value={socialUsername} onChange={e=>setSocialUsername(e.target.value)} placeholder="Username sosial"/><input className="input sm:col-span-2" value={postUrl} onChange={e=>setPostUrl(e.target.value)} placeholder="https://instagram.com/..."/></div><Button className="mt-4" loading={saving} onClick={()=>void submit()}>Kirim Pendaftaran & Bukti</Button></Card>
 </div></div>;
}
