import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ShieldCheck, GraduationCap, Trophy, AlertTriangle, Calendar, Hash } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { getPublicCertificate } from '@/services/certificate.service';
import { formatShortDate } from '@/lib/utils';

export function VerifyPage() {
  const { code } = useParams();
  const [record, setRecord] = useState<any>(null);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let alive=true; (async()=>{ try { if (code) setRecord(await getPublicCertificate(code)); } catch { setRecord(null); } finally { if (alive) setLoading(false); } })(); return()=>{alive=false;}; },[code]);
  const valid = record && ['GENERATED','REVIEW','APPROVED','PUBLISHED'].includes(record.status) && !record.revoked_at;
  return <div className="min-h-screen"><header className="glass border-b border-white/5 px-4 h-16 flex items-center justify-between"><Link to="/" className="flex items-center gap-2"><div className="w-8 h-8 rounded-lg gradient-moss flex items-center justify-center"><GraduationCap size={16} className="text-white"/></div><span className="font-display font-bold text-white">sykabelajar<span className="text-moss-400">.id</span></span></Link><Link to="/login"><Button variant="ghost" size="sm">Masuk</Button></Link></header><main className="max-w-2xl mx-auto px-4 py-8">{loading?<Card className="p-10 text-center text-slate-500">Memeriksa sertifikat…</Card>:!record?<Card className="p-10 text-center"><AlertTriangle className="mx-auto text-red-400" size={34}/><h1 className="font-display text-xl font-bold text-white mt-3">Sertifikat tidak ditemukan</h1><p className="text-sm text-slate-500 mt-2">Kode verifikasi tidak terdaftar di backend.</p></Card>:<><Card className={`p-6 text-center ${valid?'bg-moss-500/5 border-moss-500/20':'bg-red-500/5 border-red-500/20'}`}><div className={`w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-3 ${valid?'bg-moss-500/20':'bg-red-500/20'}`}><ShieldCheck size={32} className={valid?'text-moss-400':'text-red-400'}/></div><h1 className="font-display font-bold text-xl text-white">{valid?'Terverifikasi ASLI':'Sertifikat Tidak Valid'}</h1><p className="text-sm text-slate-400 mt-1">Status: {record.status}</p><Badge color={valid?'moss':'default'}>{valid?'Valid':'Tidak valid'}</Badge></Card><Card className="p-6 mt-4"><div className="text-center"><Trophy size={34} className="mx-auto text-moss-400"/><p className="text-xs text-moss-400 uppercase tracking-widest mt-3">{record.achievement_title || 'Penghargaan'}</p><p className="text-xs text-slate-500 mt-4">Diberikan kepada</p><p className="font-display text-2xl font-bold text-white mt-1">{record.public_name}</p><p className="text-sm text-slate-300 mt-3">{record.competition_title}</p></div><div className="grid grid-cols-2 gap-4 mt-6"><div><p className="text-[10px] text-slate-500">Kode</p><p className="text-xs text-moss-300 font-mono">{record.verification_code}</p></div><div><p className="text-[10px] text-slate-500">Tanggal</p><p className="text-xs text-white flex items-center gap-1"><Calendar size={11}/>{record.issued_at?formatShortDate(record.issued_at):'—'}</p></div></div></Card><Card className="p-4 mt-4"><p className="text-xs text-slate-500 flex items-center gap-2"><Hash size={13}/> ID Sertifikat</p><p className="text-xs font-mono text-slate-300 mt-1 break-all">{record.certificate_id}</p></Card></>}</main></div>;
}
